### ISSUE TITLE
🔥 Production backend is down!

### ISSUE THREAD

**Issue by JamesMGreene** [ProgramEquity/amplify#463]
From the current production deployment's logs in Heroku

```
2023-01-30T19:45:33.928875+00:00 heroku[web.1]: Starting process with command `npm start`
2023-01-30T19:45:36.327725+00:00 app[web.1]: 
2023-01-30T19:45:36.327774+00:00 app[web.1]: > amplify@1.0.0 start
2023-01-30T19:45:36.327775+00:00 app[web.1]: > node server/server.js
2023-01-30T19:45:36.327775+00:00 app[web.1]: 
2023-01-30T19:45:37.167301+00:00 app[web.1]: /app/server/auth/check-jwt.js:5
2023-01-30T19:45:37.167313+00:00 app[web.1]: const checkJwt = jwt({
2023-01-30T19:45:37.167313+00:00 app[web.1]:                  ^
2023-01-30T19:45:37.167313+00:00 app[web.1]: 
2023-01-30T19:45:37.167314+00:00 app[web.1]: TypeError: jwt is not a function
2023-01-30T19:45:37.167316+00:00 app[web.1]:     at Object.<anonymous> (/app/server/auth/check-jwt.js:5:18)
2023-01-30T19:45:37.167318+00:00 app[web.1]:     at Module._compile (node:internal/modules/cjs/loader:1165:14)
2023-01-30T19:45:37.167318+00:00 app[web.1]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
2023-01-30T19:45:37.167319+00:00 app[web.1]:     at Module.load (node:internal/modules/cjs/loader:1043:32)
2023-01-30T19:45:37.167319+00:00 app[web.1]:     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
2023-01-30T19:45:37.167319+00:00 app[web.1]:     at Module.require (node:internal/modules/cjs/loader:1067:19)
2023-01-30T19:45:37.167320+00:00 app[web.1]:     at require (node:internal/modules/cjs/helpers:103:18)
2023-01-30T19:45:37.167320+00:00 app[web.1]:     at Object.<anonymous> (/app/server/routes/api/authentication.js:9:22)
2023-01-30T19:45:37.167327+00:00 app[web.1]:     at Module._compile (node:internal/modules/cjs/loader:1165:14)
2023-01-30T19:45:37.167327+00:00 app[web.1]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
2023-01-30T19:45:37.329636+00:00 heroku[web.1]: Process exited with status 1
2023-01-30T19:45:37.414354+00:00 heroku[web.1]: State changed from starting to crashed
2023-01-30T19:46:14.975450+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/img/icons/favicon-32x32.png" host=amplify-app-production.herokuapp.com request_id=b455251e-9f21-4a24-b105-9c2f4d468f52 fwd="97.92.66.29" dyno= connect= service= status=503 bytes= protocol=https
```

## Expected Behavior

Production app should load available campaigns (and not crash)

## Current Behavior

Production app is not loaded campaigns (because the backend is crashing)

## Possible Solution

Fix the irrecoverable errors in the backend codebase. 🤷🏻‍♂️ 

## Steps to Reproduce

1. Visit https://amplify-app-production.herokuapp.com/
2. The UI is basically loaded **but** no campaigns are shown
3. If you check the developer console, you can see that the API calls to the backend are failing:
   <img width="505" alt="image" src="https://user-images.githubusercontent.com/417751/215580641-9e1befc0-a8c5-4dfc-bb4b-93dbea521bd2.png">

## Context (Environment)

Production

**Comment by JamesMGreene** [comment]
I think this was introduced in December by PR #438 

I'm speculating that the version of `express-jwt` being used right now (`8.2.0`) has a bug that it looks like the _next_ release (`8.2.1`) included a patch for: https://github.com/auth0/express-jwt/commit/2322a9b67a5b5c716f953a53a0bb4bbc696d0a11

My suggested fix would be to update `express-jwt`. Doesn't look like there is an open Dependabot PR for it, unfortunately, probably due to a maximum PR count limitation, so you may need to fix this one manually.

**Comment by paramsiddharth** [comment]
@JamesMGreene Look at this: https://github.com/ProgramEquity/amplify/pull/428#issuecomment-1396456190

Should we merge #428 then? If it is not related to the bug we can merge it and fix the version separately.

**Comment by JamesMGreene** [comment]
Merging #428 definitely won't fix it.
